### PR TITLE
Use cats-parse for parsing

### PR DESCRIPTION
**Pull request by nightscape**
This PR replaces parboiled2 by cats-parse in preparation for [Scala 3 compatibility](https://github.com/lemonlabsuk/scala-uri/issues/154).

### CODE REVIEW

**Comment by theon** [comment]
Thanks for raising this @nightscape! Once the build is passing, I'd like to run the [benchmarks](https://github.com/lemonlabsuk/scala-uri-benchmarks) and provided it shows comparable results I'll be happy to merge this. It would be nice to get a Scala 3 build published.

Looks like the build is failing at the moment because mdoc is saying one of the examples in the README is failing.

**Comment by nightscape** [comment]
Hi @theon, the tests are currently broken as well.
I either made a mistake while converting the grammar, or Parboiled2 and cats-parse work slightly differently.
I guess this will take me a few more hours to debug and fix.
Will let you know once it's ready.

**Comment by gregor-i** [comment]
@nightscape I'd like to see support of scala 3 for scala-url happening. May I support you with this PR? What need to be done next?

**Comment by nightscape** [comment]
Hey @gregor-i, that would be great! I unfortunately got pulled into other things before being able to finish this...
The last thing I remember was that I tried to get the path parsing to work with leading slashes (see the above issue in the cats-parse repo). Apart from that I moved along the test cases from simple to more complex. I'll check my local version if I have any uncommitted changes.

**Comment by nightscape** [comment]
I didn't have local changes, but I rebased on the latest master.

**Comment by theon** [comment]
Thanks again @nightscape. I have merged this in https://github.com/lemonlabsuk/scala-uri/pull/342, however still stuck for the meantime on getting a Scala 3 build. Stuck on shapeless which will unfortunately likely take some time to resolve before being able to get a Scala 3 milestone published: https://github.com/lemonlabsuk/scala-uri/pull/343

**Comment by nightscape** [comment]
Thanks @gregor-i and @theon for finalizing this!!

**Pull request closed without merging**
